### ISSUE TITLE
Purchase request

### ISSUE THREAD

**Issue by TVW74** [adamples/VU_meter#4]
Hi Adam,

Looking at your latest Youtube OLED VU meter video, I really would like to use this in my self made integrated Hypex Class-D amp with Vicol Audio Maya controller. But I have no experience and possibilties for making, programming, etc. Would it be possible to buy a full working OLED VU meter with white OLED dispays from you?

Kind regards,
Theo.

**Comment by adamples** [comment]
Hi, Thank you for your interest! Please contact me directly at ples.adam@gmail.com
